- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  class: "services-contact"
  title: "Contact"

- name: "RSS Feed"
  url: "/feed.xml"
  class: "rss-link"
  title: "Subscribe to RSS"

- name: "Podcast Feed"
  url: "/podcast.xml"
  class: "rss-link"
  title: "Subscribe to Podcast feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Sitemap for Google Webmastertools"
